export const namesOfExercises = [
        {value:"bench-press",name:"Bench Press"},
        {value:"deadlift",name:"Deadlift"},
        {value:"squat",name:"Squat"},
        {value:"shoulder-press",name:"Shoulder Press"},
        {value:"barbell-curl",name:"Barbell Curl"},
        {value:"military-press",name:"Military Press"},
        {value:"front-squat",name:"Front Squat"},
        {value:"incline-bench-press",name:"Incline Bench Press"},
        {value:"bent-over-row",name:"Bent Over Row"},
        {value:"hex-bar-deadlift",name:"Hex Bar Deadlift"},
        {value:"sumo-deadlift",name:"Sumo Deadlift"},
        {value:"hip-thrust",name:"Hip Thrust"},
        {value:"romanian-deadlift",name:"Romanian Deadlift"},
        {value:"close-grip-bench-press",name:"Close Grip Bench Press"},
        {value:"pendlay-row",name:"Pendlay Row"},
        {value:"stiff-legged-deadlift",name:"Stiff Legged Deadlift"},
        {value:"decline-bench-press",name:"Decline Bench Press"},
        {value:"tricep-extension",name:"Tricep Extension"},
        {value:"t-bar-row",name:"T-Bar Row"},
        {value:"rack-pull",name:"Rack Pull"},
        {value:"barbell-shrug",name:"Barbell Shrug"},
        {value:"box-squat",name:"Box Squat"},
        {value:"barbell-lunge",name:"Barbell Lunge"},
        {value:"zercher-squat",name:"Zercher Squat"},
        {value:"preacher-curl",name:"Preacher Curl"},
        {value:"upright-row",name:"Upright Row"},
        {value:"lying-tricep-extension",name:"Lying Tricep Extension"},
        {value:"good-morning",name:"Good Morning"},
        {value:"reverse-wrist-curl",name:"Reverse Wrist Curl"},
        {value:"bulgarian-split-squat",name:"Bulgarian Split Squat"},
        {value:"floor-press",name:"Floor Press"},
        {value:"wrist-curl",name:"Wrist Curl"},
        {value:"split-squat",name:"Split Squat"},
        {value:"landmine-squat",name:"Landmine Squat"},
        {value:"pull-ups",name:"Pull Ups"},
        {value:"push-ups",name:"Push Ups"},
        {value:"dips",name:"Dips"},
        {value:"chin-ups",name:"Chin Ups"},
        {value:"bodyweight-squat",name:"Bodyweight Squat"},
        {value:"muscle-ups",name:"Muscle Ups"},
        {value:"sit-ups",name:"Sit Ups"},
        {value:"burpees",name:"Burpees"},
        {value:"single-leg-squat",name:"Single Leg Squat"},
        {value:"crunches",name:"Crunches"},
        {value:"one-arm-push-ups",name:"One Arm Push Ups"},
        {value:"handstand-push-ups",name:"Handstand Push Ups"},
        {value:"lunge",name:"Lunge"},
        {value:"power-clean",name:"Power Clean"},
        {value:"clean-and-jerk",name:"Clean and Jerk"},
        {value:"clean",name:"Clean"},
        {value:"snatch",name:"Snatch"},
        {value:"push-press",name:"Push Press"},
        {value:"clean-and-press",name:"Clean and Press"},
        {value:"overhead-squat",name:"Overhead Squat"},
        {value:"push-jerk",name:"Push Jerk"},
        {value:"thruster",name:"Thruster"},
        {value:"power-snatch",name:"Power Snatch"},
        {value:"dumbbell-bench-press",name:"Dumbbell Bench Press"},
        {value:"dumbbell-curl",name:"Dumbbell Curl"},
        {value:"dumbbell-shoulder-press",name:"Dumbbell Shoulder Press"},
        {value:"incline-dumbbell-bench-press",name:"Incline Dumbbell Bench Press"},
        {value:"dumbbell-row",name:"Dumbbell Row"},
        {value:"dumbbell-lateral-raise",name:"Dumbbell Lateral Raise"},
        {value:"dumbbell-hammer-curl",name:"Dumbbell Hammer Curl"},
        {value:"arnold-press",name:"Arnold Press"},
        {value:"dumbbell-fly",name:"Dumbbell Fly"},
        {value:"dumbbell-shrug",name:"Dumbbell Shrug"},
        {value:"goblet-squat",name:"Goblet Squat"},
        {value:"dumbbell-bulgarian-split-squat",name:"Dumbbell Bulgarian Split Squat"},
        {value:"dumbbell-lunge",name:"Dumbbell Lunge"},
        {value:"dumbbell-tricep-extension",name:"Dumbbell Tricep Extension"},
        {value:"dumbbell-front-raise",name:"Dumbbell Front Raise"},
        {value:"dumbbell-concentration-curl",name:"Dumbbell Concentration Curl"},
        {value:"incline-dumbbell-curl",name:"Incline Dumbbell Curl"},
        {value:"lying-dumbbell-tricep-extension",name:"Lying Dumbbell Tricep Extension"},
        {value:"incline-dumbbell-fly",name:"Incline Dumbbell Fly"},
        {value:"dumbbell-pullover",name:"Dumbbell Pullover"},
        {value:"dumbbell-reverse-fly",name:"Dumbbell Reverse Fly"},
        {value:"decline-dumbbell-bench-press",name:"Decline Dumbbell Bench"},
        {value:"sled-leg-press",name:"Sled Leg Press"},
        {value:"horizontal-leg-press",name:"Horizontal Leg Press"},
        {value:"chest-press",name:"Chest Press"},
        {value:"leg-extension",name:"Leg Extension"},
        {value:"calf-raise",name:"Calf Raise"},
        {value:"machine-shoulder-press",name:"Machine Shoulder Press"},
        {value:"vertical-leg-press",name:"Vertical Leg Press"},
        {value:"lying-leg-curl",name:"Lying Leg Curl"},
        {value:"pec-deck-fly",name:"Pec Deck Fly"},
        {value:"seated-leg-curl",name:"Seated Leg Curl"},
        {value:"seated-calf-raise",name:"Seated Calf Raise"},
        {value:"hack-squat",name:"Hack Squat"},
        {value:"hip-abduction",name:"Hip Abduction"},
        {value:"hip-adduction",name:"Hip Adduction"},
        {value:"lat-pulldown",name:"Lat Pulldown"},
        {value:"seated-cable-row",name:"Seated Cable Row"},
        {value:"tricep-pushdown",name:"Tricep Pushdown"},
        {value:"tricep-rope-pushdown",name:"Tricep Rope Pushdown"},
        {value:"cable-fly",name:"Cable Fly"},
        {value:"face-pull",name:"Face Pull"}
            ];